export const BOOK_SLOT_START = "BOOK_SLOT_START";
export const BOOK_SLOT_FAILURE = "BOOK_SLOT_FAILURE";
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SUCCESS";

export const CHOOSE_SLOT = "CHOOSE_SLOT";

export const DELETE_SLOT_START = "DELETE_SLOT_START";
export const DELETE_SLOT_FAILURE = "DELETE_SLOT_FAILURE";
export const DELETE_SLOT_SUCCESS = "DELETE_SLOT_SUCCESS";

export const GET_DETAILS_START = "GET_DETAILS_START";
export const GET_DETAILS_FAILURE = "GET_DETAILS_FAILURE";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";

export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
