export const CHOOSE_SLOT = "CHOOSE_SLOT";
export const BOOK_SLOT_START = "BOOK_SLOT_START";
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SUCCESS";
export const BOOK_SLOT_FAILURE = "BOOK_SLOT_FAILURE";
export const DELETE_SLOT_START = "DELETE_SLOT_START";
export const DELETE_SLOT_SUCCESS = "DELETE_SLOT_SUCCESS";
export const DELETE_SLOT_FAILURE = "DELETE_SLOT_FAILURE";
