export const SET_DATE = "SET_DATE";
export const GET_SLOTS_FAILURE = "GET_SLOTS_FAILURE";
export const GET_SLOTS_SUCCESS = "GET_SLOTS_SUCCESS";
export const RESET_BOOKINGS = "RESET_BOOKINGS";
export const SELECT_SLOT = "SELECT_SLOT";
